# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# bdefault_platform(:ios)

platform :ios do
  lane :screenshots do
    capture_screenshots(workspace: "SeedTool.xcworkspace", scheme: "SeedToolUITests")
    # upload_to_app_store(skip_binary_upload: true, overwrite_screenshots: true)
  end

  lane :upload_metadata do
    upload_to_app_store(skip_binary_upload: true, overwrite_screenshots: true)
  end

  lane :beta do
#    ensure_git_status_clean
#    increment_build_number
#    commit_version_bump
#    add_git_tag
#    push_to_git_remote
    build_ios_app(
        scheme: "SeedTool"
        output_directory: "./build-ios",
    )
#    upload_to_testflight(
#        app_platform: "ios"
#    )
  end
end

platform :mac do
    lane :beta do
        build_mac_app(
            scheme: "SeedTool",
            destination: "generic/platform=macOS,variant=Mac Catalyst,name=Any Mac",
            output_directory: "./build-mac",
            xcargs: "-allowProvisioningUpdates"
        )
#        upload_to_testflight(
#            app_platform: "mac"
#        )
    end
end
