devices([
  "iPhone 8 Plus",
  "iPhone 11 Pro Max",
  "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (12.9-inch) (4th generation)"
])

languages([
  "en-US"
])

scheme("GuardianUITests")
clear_previous_screenshots(true)
erase_simulator(true)
override_status_bar(true)
dark_mode(true)
disable_slide_to_type(true)

# For more information about all available options run
# fastlane action snapshot
